language: node_js


branches:
  only:
    - master

node_js:
  - "4"
  - "5"

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa
  - sudo apt-get update
  - sudo apt-get install rethinkdb

before_script:
  - rethinkdb --daemon
  - "npm install"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com