language: node_js

services:
  - rethinkdb

branches:
  only:
    - master

node_js:
  - "4"
  - "5"

before_script:
  - "npm install"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com